### ISSUE TITLE
Missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [elan-ev/moodle-local_och5pcore#1]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin doesn't appear to store any user data so you should be able to implement the simple null provider class.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by ferishili** [comment]
Hi @danmarsden, thanks again and sorry for the long delay.
This issue is completed in https://github.com/elan-ev/moodle-local_och5pcore/commit/49d03e128accee9f1e02265767d41c73f4fbe940
