### ISSUE TITLE
add dependencie on mod_lti to version.php

### ISSUE THREAD

**Issue by danmarsden** [elan-ev/moodle-local_och5pcore#3]
although mod_lti is a core plugin, as your code relies on it, it's good practice to add a dependency for it into version.php - it's possible (although unlikely) that a site might delete the mod/lti plugin from their codebase.

not a blocker for approval - just a nice thing to add.

**Comment by ferishili** [comment]
Hi @danmarsden, thanks again and sorry for the long delay.
Unfortunately, adding this dependency may result in bothering some institutions, therefore, I don't add it.
