### ISSUE TITLE
renderes.php with "Boost Union" Theme not working

### ISSUE THREAD

**Issue by fsufrre** [elan-ev/moodle-local_och5pcore#4]
Opencast H5P Extension uses the suggested method of h5p to provide custom script and style for both mod_hvp and core h5p into moodle, which is extending the renderers.php in themes. The Boost Union recently provides this feature in this commit https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commits/master/renderers.php which is the exact same thing that och5p plugins were using since the beginning!

Therefore, och5p plugins assume that those extensions are already there and they skip, but what is missing is to load the js files and css files related to use Opencast in the H5P content!

**Comment by ferishili** [comment]
Closed as completed!
