### ISSUE TITLE
Opencast videos missing when editing H5P content in course (Interactive Video)

### ISSUE THREAD

**Issue by adnbes** [elan-ev/moodle-local_och5pcore#5]
Hi, i think there is an issue with the opencast videos.

**Content Bank:**
- Add -> Interactive Video
- Add file -> Opencast Video -> Select a video file -> Save
- Edit -> Add file – Opencast videos are visible

**Course:**
- Create an activity -> H5P
- Package file -> Interactive Video from the content bank -> Save
- Select the H5P activity -> Click -> Edit H5P content
**- Click on Add file – Opencast videos are NOT visible.**

If you add the parameter &contextid=...... (where the number corresponds to the one in the parameter URL), the Opencast videos become visible again.

Moodle: 4.3.7 (Build: 20240902)

**Comment by ferishili** [comment]
Hi,
that is the **core** version of the Opencast H5P Integration, and it is designed to only provide this feature via Moodle core Content Bank.
If you would like to also have this feature in the H5P Plugin (aka H5P activity) you need to install and configure this plugin:
https://github.com/Opencast-Moodle/moodle-local_och5p

There are helpful documents worth noticing:
- https://github.com/Opencast-Moodle/moodle-local_och5p/blob/master/README.md#moodle-local_och5p
- https://github.com/elan-ev/moodle-local_och5pcore?tab=readme-ov-file#moodle-local_och5pcore
- https://moodle.org/plugins/local_och5pcore

**Comment by ferishili** [comment]
Closed as answered!
